### ISSUE TITLE
DFT generation with 1 sample per cycle fails

### ISSUE THREAD

**Issue by ghost** [fserre/sgen#8]
I changed the project version from 1.5.5 to 1.8.0 to get around a Java issue like this related to sbt not starting:
https://github.com/sbt/sbt/issues/6925

Now the generator runs, but not if I select n=6, k=0 (1 sample per cycle). With n=6, k=1 it works fine. Or with n=6, k=6 it also works fine. See below for the NoSuchElementException:

```
sbt "run -n 6 -k 0 -hw complex fixedpoint 16 0 -dualramcontrol -o sgen_dft.v dft"
[info] welcome to sbt 1.8.0 (Homebrew Java 19.0.1)
[info] loading project definition from /Users/<user>/git/SGen/project
[info] loading settings for project root from build.sbt ...
[info] set current project to SGen (in build file:/Users/<user>/git/SGen/)
[info] running (fork) Main -n 6 -k 0 -hw complex fixedpoint 16 0 -dualramcontrol -o sgen_dft.v dft
[info]    _____ ______          SGen v.0.2 - A Generator of Streaming Hardware
[info]   / ___// ____/__  ____  Department of Computer Science, ETH Zurich, Switzerland
[info]   \__ \/ / __/ _ \/ __ \
[info]  ___/ / /_/ /  __/ / / / Copyright (C) 2020-2021 François Serre (serref@inf.ethz.ch)
[info] /____/\____/\___/_/ /_/  https://github.com/fserre/sgen
[info] This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it and to modify it under the terms of the GNU GPLv3+ <http://gnu.org/licenses/gpl.html>.
[error] Exception in thread "main" java.util.NoSuchElementException: empty.head
[error] 	at scala.collection.immutable.Vector.head(Vector.scala:277)
[error] 	at Main$.r$1(Main.scala:62)
[error] 	at Main$.main(Main.scala:153)
[error] 	at Main.main(Main.scala)
[error] Nonzero exit code returned from runner: 1
[error] (Compile / run) Nonzero exit code returned from runner: 1
[error] Total time: 1 s, completed Dec 12, 2022, 3:17:50 PM

```

**Comment by ghost** [comment]
Maybe it's unrelated to the sbt version and you just don't support a fully-pipelined version that accepts exactly 1 complex sample per cycle?

**Comment by LightCannon** [comment]
> Reference i
Hello. Have you reached any update regarding this? I cannot generate a single input DFT

**Comment by LightCannon** [comment]
> Maybe it's unrelated to the sbt version and you just don't support a fully-pipelined version that accepts exactly 1 complex sample per cycle?

Hello. Have you reached any update regarding this? I cannot generate a single input DFT

**Comment by ghost** [comment]
I found that this particular FFT generator simply doesn't support a
1-sample-per-cycle use case. But, it's a very high quality generator for
all other settings. It compares favorably with Spiral, for example (I did a
benchmark on utilization).
